#!/bin/bash
# Railway Variables Verification Script
# Run this interactively in your terminal

echo "🔍 Railway Environment Variables Check"
echo "========================================"
echo ""
echo "You're logged in as: $(railway whoami)"
echo "Project: $(railway status | grep Project | cut -d: -f2 | xargs)"
echo ""

echo "📦 Step 1: Check BrainScraper Service"
echo "--------------------------------------"
echo "Run these commands:"
echo "  cd brainscraper"
echo "  railway service  # Select 'brainscraper' service"
echo "  railway variables"
echo ""
echo "✅ Verify these are set:"
echo "  - REDIS_URL (should use \${{redis-bridge.REDIS_URL}})"
echo "  - RAPIDAPI_KEY"
echo "  - NODE_ENV=production"
echo "  - PORT=3000"
echo "  - NEXT_PUBLIC_BASE_URL"
echo "  - DATA_DIR=/data"
echo ""
read -p "Press Enter when done checking BrainScraper..."

echo ""
echo "📦 Step 2: Check Scrapegoat Service"
echo "--------------------------------------"
echo "Run these commands:"
echo "  cd scrapegoat"
echo "  railway service  # Select 'scrapegoat' service"
echo "  railway variables"
echo ""
echo "✅ Verify these are set:"
echo "  - DATABASE_URL (should use \${{PostgreSQL.DATABASE_URL}})"
echo "  - REDIS_URL (should use \${{redis-bridge.REDIS_URL}})"
echo "  - CAPSOLVER_API_KEY=CAP-2540716108BC4D181465BF715D674904421D53CB7CE512D511EC80DEDB3744DD ⭐ NEW"
echo "  - DECODO_API_KEY (for proxy rotation)"
echo "  - OPENAI_API_KEY"
echo "  - CENSUS_API_KEY"
echo "  - PYTHONUNBUFFERED=1"
echo ""
read -p "Press Enter when done checking Scrapegoat..."

echo ""
echo "📦 Step 3: Check Scrapegoat Worker Service"
echo "--------------------------------------"
echo "Run these commands:"
echo "  cd scrapegoat"
echo "  railway service  # Select 'scrapegoat-worker' service"
echo "  railway variables"
echo ""
echo "✅ CRITICAL: Verify these are set (same as Scrapegoat):"
echo "  - DATABASE_URL"
echo "  - REDIS_URL"
echo "  - CAPSOLVER_API_KEY=CAP-2540716108BC4D181465BF715D674904421D53CB7CE512D511EC80DEDB3744DD ⭐ CRITICAL"
echo "  - DECODO_API_KEY"
echo "  - OPENAI_API_KEY"
echo "  - CENSUS_API_KEY"
echo "  - PYTHONUNBUFFERED=1"
echo ""
read -p "Press Enter when done checking Scrapegoat Worker..."

echo ""
echo "✅ Verification Complete!"
echo ""
echo "🚨 Most Important NEW Variables:"
echo "  1. CAPSOLVER_API_KEY - Must be in BOTH Scrapegoat AND Worker"
echo "  2. DECODO_API_KEY - Must be in BOTH Scrapegoat AND Worker"
echo ""
echo "💡 If any are missing, set them with:"
echo "  railway variables --set 'KEY=value'"
