import { Octokit } from "@octokit/rest";
import type { ScraperBlueprint } from "../app/dojo/types";

/**
 * GithubDeployer - Auto-Deploy generated scrapers via Pull Request
 * 
 * Creates PRs with full context:
 * - The Blueprint JSON (contract)
 * - The Generation Instructions (architecture)
 * - The Generated Code (implementation)
 */
export class GithubDeployer {
  private octokit: Octokit;
  private owner: string;
  private repo: string;

  constructor() {
    const token = process.env.GITHUB_TOKEN;
    const owner = process.env.GITHUB_OWNER;
    const repo = process.env.GITHUB_REPO;

    if (!token || !owner || !repo) {
      throw new Error(
        "Missing GitHub configuration. Set GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO."
      );
    }

    this.octokit = new Octokit({ auth: token });
    this.owner = owner;
    this.repo = repo;
  }

  /**
   * Create a Pull Request with the generated scraper code
   */
  async createScraperPR(
    code: string,
    blueprint: ScraperBlueprint,
    instructions: string
  ): Promise<{ prUrl: string; branchName: string }> {
    const filename = `scrapegoat/app/scraping/spiders/${blueprint.filename}`;

    // 1. "The Cage": Strict Path Validation
    if (!filename.startsWith("scrapegoat/app/scraping/spiders/")) {
      throw new Error(
        "Security Violation: Can only write to spiders directory."
      );
    }

    if (!filename.endsWith(".py")) {
      throw new Error("Security Violation: File must be a Python file (.py)");
    }

    // Sanitize filename to prevent path traversal
    if (filename.includes("..") || filename.includes("//")) {
      throw new Error("Security Violation: Invalid path characters detected.");
    }

    // 2. Setup Branch
    const timestamp = Date.now();
    const sanitizedId = blueprint.id.replace(/[^a-z0-9_-]/gi, "_");
    const branchName = `dojo/bot-${sanitizedId}-${timestamp}`;

    // Get main branch SHA
    const { data: mainRef } = await this.octokit.git.getRef({
      owner: this.owner,
      repo: this.repo,
      ref: "heads/main",
    });

    // Create new branch
    await this.octokit.git.createRef({
      owner: this.owner,
      repo: this.repo,
      ref: `refs/heads/${branchName}`,
      sha: mainRef.object.sha,
    });

    // 3. Commit File
    await this.octokit.repos.createOrUpdateFileContents({
      owner: this.owner,
      repo: this.repo,
      path: filename,
      message: `feat(scraper): Add ${blueprint.id} spider via Dojo`,
      content: Buffer.from(code).toString("base64"),
      branch: branchName,
    });

    // 4. Construct Rich PR Body (The Context)
    const prBody = this.buildPRBody(blueprint, instructions);

    // 5. Open PR
    const { data: pr } = await this.octokit.pulls.create({
      owner: this.owner,
      repo: this.repo,
      title: `🤖 Dojo: Add ${blueprint.responseModelName} Spider`,
      head: branchName,
      base: "main",
      body: prBody,
    });

    return {
      prUrl: pr.html_url,
      branchName,
    };
  }

  /**
   * Build a rich, context-aware PR body with documentation
   */
  private buildPRBody(blueprint: ScraperBlueprint, instructions: string): string {
    const headerEmoji = blueprint.method === "GET" ? "📥" : "📤";
    
    return `# 🤖 New Scraper: ${blueprint.responseModelName}

${headerEmoji} **Target:** \`${blueprint.targetUrl}\`
📡 **Method:** \`${blueprint.method}\`
📁 **File:** \`scrapegoat/app/scraping/spiders/${blueprint.filename}\`

---

## 📋 Blueprint Specification

> This JSON defines the contract for this scraper. It was generated by The Dojo's AI analysis of captured HTTP traffic.

<details>
<summary>Click to expand Blueprint JSON</summary>

\`\`\`json
${JSON.stringify(blueprint, null, 2)}
\`\`\`

</details>

---

## 🏗️ Architecture Instructions

> The following "Mega-Prompt" was used to generate this spider code. It serves as architectural documentation.

<details>
<summary>Click to expand Generation Instructions</summary>

\`\`\`text
${instructions}
\`\`\`

</details>

---

## ✅ Pre-Merge Checklist

- [ ] Review Pydantic models match actual API response
- [ ] Verify essential headers are correct
- [ ] Check error handling for edge cases
- [ ] Test with sample request

---

## 🔗 Related

- Generated by **The Dojo Auto-Coder**
- Blueprint ID: \`${blueprint.id}\`
- Created: ${new Date(blueprint.createdAt).toISOString()}
`;
  }

  /**
   * Check if GitHub integration is configured
   */
  static isConfigured(): boolean {
    return !!(
      process.env.GITHUB_TOKEN &&
      process.env.GITHUB_OWNER &&
      process.env.GITHUB_REPO
    );
  }
}
